version: '3.9'

services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: middleware
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/v1/health-check/ws" ]
      interval: 5s
      start_period: 10s
      retries: 1000
      timeout: 5s
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - local-network

  caddy:
    image: caddy:alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - middleware
    networks:
      - local-network
    volumes:
        - ./devops/Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config

networks:
  local-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
